### ISSUE TITLE
Avoid encoding same IP repeatedly

### ISSUE THREAD

**Issue by ajvondrak** [KineticCafe/ip_access_control#1]
Hey, I was just taking a look at your code due to ajvondrak/remote_ip#27, and noticed this line:
https://github.com/KineticCafe/ip_access_control/blob/f23b7c0b54ac783de3795571ec3164946a70b50a/lib/ip_access_control.ex#L196

I wanted to point out that encoding the IP takes a relatively long time. Enough that it can outweigh any gains `RemoteIp.Block.contains?/2` has on its own in a single call: https://github.com/ajvondrak/remote_ip/commit/d1431f902362340922abf009dd4aaf97505dc637

As long as the compiler isn't sufficiently smart (which is my conservative assumption), this line is encoding the same IP repeatedly. Just to make sure this doesn't happen, you could perform some manual [loop-invariant code motion](https://en.wikipedia.org/wiki/Loop-invariant_code_motion):

```elixir
  def allowed?(remote_ip, allow_list) when is_tuple(remote_ip) do
    encoded_ip = RemoteIp.Block.encode(remote_ip)

    allow_list
    |> parse_allow_list()
    |> Enum.any?(&RemoteIp.Block.contains?(&1, encoded_ip))
  end
```

This is similar to the code in remote\_ip: https://github.com/ajvondrak/remote_ip/blob/4826fc437976d7e8dca1ac0ed1ebc7459c6b1a33/lib/remote_ip.ex#L271-L286

(Disclaimer: this is all squarely in the camp of "majoring in the minors". No one's likely to notice the actual performance difference. But it makes me _feel_ better knowing it's more efficient. 😂)

**Comment by halostatue** [comment]
I had fixed something like that elsewhere (probably in my tests) and just missed it there. Your suggestion is eminently viable. Thanks!
